services:
  zookeeper:
      image: confluentinc/cp-zookeeper:7.5.1
      ports:
        - "2181:2181"
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost

  ksqldb-server:
    image: confluentinc/cp-ksqldb-server:7.5.1
    depends_on:
      - kafka
    ports:
      - "8088:8088"
    volumes:
      - ./ksqldb/daily_cash_flow.sql:/etc/ksql/daily_cash_flow.sql
    environment:
      KSQL_CONFIG_DIR: "/etc/ksql"
      KSQL_BOOTSTRAP_SERVERS: "kafka:9092"
      KSQL_HOST_NAME: ksqldb-server
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_CACHE_MAX_BYTES_BUFFERING: 0
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_REPLICATION_FACTOR: 1
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: 'true'
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: 'true'
      KSQL_KSQL_QUERIES_FILE: /etc/ksql/daily_cash_flow.sql

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.5.1
    depends_on:
      - kafka
      - ksqldb-server
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONTROL_CENTER_KSQL_KSQLDB1_URL: "http://ksqldb-server:8088"
      CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL: "http://localhost:8088"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021

  mongo-users:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: users
    deploy:
      resources:
        limits:
          cpus: '3'

  mongo-transactions:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: transactions
    deploy:
      resources:
        limits:
          cpus: '3'

  mongo-dailycashflow:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: dailycashflow
    deploy:
      resources:
        limits:
          cpus: '3'

  users-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: Users
    depends_on:
      - mongo-users
    environment:
      MongoConnectionString: mongodb://mongo-users:27017
      MongoDatabase: users
    restart: on-failure
    deploy:
      replicas: 3

  transactions-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: Transactions
    depends_on:
      - mongo-transactions
    environment:
      MongoConnectionString: mongodb://mongo-transactions:27017
      MongoDatabase: transactions
      KafkaServers: kafka:9092
    restart: on-failure
    deploy:
      replicas: 3

  dailycashflow-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: DailyCashFlow
    depends_on:
      - mongo-dailycashflow
    environment:
      MongoConnectionString: mongodb://mongo-dailycashflow:27017
      MongoDatabase: dailycashflow
    restart: on-failure
    deploy:
      replicas: 3

  dailycashflow-consumer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: DailyCashFlowConsumer
    depends_on:
      - mongo-dailycashflow
    environment:
      MongoConnectionString: mongodb://mongo-dailycashflow:27017
      MongoDatabase: dailycashflow
      KafkaServers: kafka:9092
      ThreadsPerCosnumer: 1
    restart: on-failure
    deploy:
      replicas: 1

  console:
    build:
      context: ./console
      dockerfile: Dockerfile
    environment:
      USERS_MONGO_URL: mongodb://mongo-users:27017
      TRANSACTIONS_MONGO_URL: mongodb://mongo-transactions:27017
      DAILY_CASH_FLOW_MONGO_URL: mongodb://mongo-dailycashflow:27017

  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - users-api
      - transactions-api
      - dailycashflow-api
    restart: on-failure
